import type { Tour } from 'nextstepjs';

export const tourSteps: Tour[] = [
  {
    tour: 'onboarding',
    steps: [
      {
        icon: '',
        title: 'Willkommen bei Havoc!',
        content: <>Lass uns kurz durch die wichtigsten Bereiche gehen — dauert nur eine Minute.</>,
        showControls: true,
        showSkip: true,
      },
      {
        icon: '',
        title: 'Dein Dashboard',
        content: <>Hier siehst du auf einen Blick wie deine Agents performen — aktive Agents, Nachrichten, Kosten.</>,
        selector: '#tour-dashboard',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
        nextRoute: '/dashboard',
      },
      {
        icon: '',
        title: 'KPIs im Überblick',
        content: <>Diese Karten zeigen dir die wichtigsten Zahlen: aktive Agents, Nachrichten, AI-Kosten und verbundene Kanäle.</>,
        selector: '#tour-kpis',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '',
        title: 'Agents verwalten',
        content: <>Hier erstellst und verwaltest du deine AI Agents. Jeder Agent hat eigene Skills, Kanäle und eine Persönlichkeit.</>,
        selector: '#tour-agents',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 4,
        pointerRadius: 8,
        nextRoute: '/agents',
      },
      {
        icon: '',
        title: 'Neuen Agent erstellen',
        content: <>Klick hier um einen neuen AI Mitarbeiter zu erstellen — per AI Builder oder aus einer Vorlage.</>,
        selector: '#tour-create-agent',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 12,
        pointerRadius: 16,
      },
      {
        icon: '',
        title: 'Knowledge Base',
        content: <>Hier verwaltest du das Wissen deiner Agents — alles was sie brauchen um gute Antworten zu geben.</>,
        selector: '#tour-knowledge',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 4,
        pointerRadius: 8,
        nextRoute: '/knowledge',
      },
      {
        icon: '',
        title: 'Quellen hinzufügen',
        content: <>Lade PDFs, Texte oder ganze Websites hoch. Deine Agents nutzen diese Dokumente als Wissensgrundlage.</>,
        selector: '#tour-knowledge-sources',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '',
        title: 'Integrationen',
        content: <>Verbinde Google Drive oder Notion — deine Agents haben dann automatisch Zugriff auf aktuelle Dokumente.</>,
        selector: '#tour-knowledge-integrations',
        side: 'top',
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
      },
      {
        icon: '',
        title: 'Bereit!',
        content: <>Du kennst jetzt die wichtigsten Bereiche. Erstelle deinen ersten AI Mitarbeiter und leg los!</>,
        showControls: true,
        showSkip: false,
        nextRoute: '/dashboard',
      },
    ],
  },
];
